### PR TITLE
add Weekly report

### PR DESCRIPTION
**Pull request by yuanyiwei**

### CODE REVIEW

**Comment by iBug** [comment]
Not good coding styles, including use of spaces, parentheses, error handling, and most importantly regexes.

I've already pushed 50d6bfbe57d3ef5102e7b1011e3335d573cc7da3 so closing this now.

**Comment by yuanyiwei** [comment]
I think your way of getting `start_date` is wrong and lacking checks for weekly report...

**Comment by yuanyiwei** [comment]
Oh you updated it.

**Comment by iBug** [comment]
I suspect that the server disregards `start_date` and `end_date` from POST data, so whatever we put in there doesn't matter.

FYI, it seems the server was updated yesterday (Nov. 30) and...

image

**Comment by yuanyiwei** [comment]
> I think your way of getting `start_date` is wrong and lacking checks for weekly report...

I don’t think it should find the word '在校已出校报备'.
These shouldn't run when at home.

Instead it shoud have check on `if data["is_inschool"] == is_inschool` or find '在校未出校报备'.

**Comment by iBug** [comment]
> Instead it shoud have check on `if data["is_inschool"] == is_inschool` or find '在校未出校报备'.

Makes sense, done in 263842592b171e69ff42d3b40c65ec0a0a75d174.

**Pull request closed without merging**
